const REFRESH_TOKEN_EXPIRED = 30 * 24 * 60 * 60 * 1000;
const TOKEN_EXPIRED = 7 * 24 * 60 * 60 * 1000;
const REFRESH_TOKEN_NAME = "refreshToken";
const TOKEN_NAME = "jwtToken";

module.exports = { REFRESH_TOKEN_EXPIRED, TOKEN_EXPIRED, TOKEN_NAME, REFRESH_TOKEN_NAME };